version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npx -y rimraf node_modules ios android &&
             npm install &&
             npx -y expo prebuild --platform android &&
             cd android &&
             ./gradlew assembleRelease"
    volumes:
      - "./:/app"
